import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      layout: {
        logoImageUrl: "/icons/logo.svg",
        socialButtonsVariant:'iconButton'
      },variables: {
        colorText: 'white',
        colorPrimary: '#0E7879',
        colorBackground: '#1C1F2E',
        colorInputBackground: '#252A41',
        colorInputText: '#FFF'
      }
    }}>
      <html lang="en">
      <body className={`${inter.className} bg-dark-2`}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
